from enum import Enum


class TicketStatus(str, Enum):
    NEW = "NEW"
    PARSED = "PARSED"
    VALIDATED = "VALIDATED"
    WAITING_FOR_INFORMATION = "WAITING_FOR_INFORMATION"
    READY_FOR_SCHEDULING = "READY_FOR_SCHEDULING"
    PENDING_USER_APPROVAL = "PENDING_USER_APPROVAL"
    ACCEPTED = "ACCEPTED"
    CALENDAR_CREATED = "CALENDAR_CREATED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"
