"""add foreign key constraints

Revision ID: 213eea8e6750
Revises: de3df2e3b3d0
Create Date: 2026-07-11 17:50:45.663605

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '213eea8e6750'
down_revision: str | Sequence[str] | None = 'de3df2e3b3d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ai_logs_ticket_id', 'tickets', ['ticket_id'], ['ticket_id'])

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_calendar_events_ticket_id', 'tickets', ['ticket_id'], ['ticket_id'])

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_emails_ticket_id', 'tickets', ['ticket_id'], ['ticket_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint('fk_emails_ticket_id', type_='foreignkey')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_events_ticket_id', type_='foreignkey')

    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ai_logs_ticket_id', type_='foreignkey')

    # ### end Alembic commands ###
