"""add email model

Revision ID: d673f9ef1d45
Revises: 43b9e1ef282c
Create Date: 2026-07-11 17:44:57.852046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd673f9ef1d45'
down_revision: Union[str, Sequence[str], None] = '43b9e1ef282c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_time', sa.DateTime(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('email_id'),
    sa.UniqueConstraint('entry_id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_emails_conversation_id'))

    op.drop_table('emails')
    # ### end Alembic commands ###
