from backend.app.prompts.conversation_summary import (
    CONVERSATION_SUMMARY_SYSTEM,
    CONVERSATION_SUMMARY_VERSION,
)
from backend.app.prompts.email_classification import (
    EMAIL_CLASSIFICATION_SYSTEM,
    EMAIL_CLASSIFICATION_USER,
    EMAIL_CLASSIFICATION_VERSION,
)
from backend.app.prompts.email_extraction import (
    EMAIL_EXTRACTION_SYSTEM,
    EMAIL_EXTRACTION_USER,
    EMAIL_EXTRACTION_VERSION,
)
from backend.app.prompts.missing_info_draft import (
    MISSING_INFO_DRAFT_SYSTEM,
    MISSING_INFO_DRAFT_USER,
    MISSING_INFO_DRAFT_VERSION,
)
from backend.app.prompts.schedule_suggestion import (
    SCHEDULE_SUGGESTION_SYSTEM,
    SCHEDULE_SUGGESTION_USER,
    SCHEDULE_SUGGESTION_VERSION,
)

__all__ = [
    "CONVERSATION_SUMMARY_SYSTEM",
    "CONVERSATION_SUMMARY_VERSION",
    "EMAIL_CLASSIFICATION_SYSTEM",
    "EMAIL_CLASSIFICATION_USER",
    "EMAIL_CLASSIFICATION_VERSION",
    "EMAIL_EXTRACTION_SYSTEM",
    "EMAIL_EXTRACTION_USER",
    "EMAIL_EXTRACTION_VERSION",
    "MISSING_INFO_DRAFT_SYSTEM",
    "MISSING_INFO_DRAFT_USER",
    "MISSING_INFO_DRAFT_VERSION",
    "SCHEDULE_SUGGESTION_SYSTEM",
    "SCHEDULE_SUGGESTION_USER",
    "SCHEDULE_SUGGESTION_VERSION",
]
